// Dialog windows
#define MRM_LoginWindow          1
#define MRM_SettingsWindow       2
#define MRM_SingleEntryWindow	   3
#define MRM_AboutBox             4
#define MRM_MessageChooser       5
#define MRM_Progress             6
#define MRM_AudioDeviceSelection 7
#define MRM_AudioVolumeControl   8

// Session Manager menus
#define MRM_BuddyListPopup          5
#define MRM_BuddyPopup              4
#define MRM_SessionManagerBackPopup	3
#define MRM_SessionManagerPopup	    2
#define MRM_SessionManagerMenu	    1

// Session Manager menu items
#define MRM_StartSession    101
#define MRM_CreateSession   102
#define MRM_EditSession     103
#define MRM_DeleteSession   104
#define MRM_ExitAll         105
#define MRM_SelectAll       106
#define MRM_DeselectAll     107
#define MRM_SessionSettings 108
#define MRM_SetAlias        109
#define MRM_RemoveBuddy     110
#define MRM_SendMessage     111
#define MRM_ProfileRefresh  112
#define MRM_SessionStatus   113
#define MRM_NewBuddy        114
#define MRM_GlobalSettings  115
#define MRM_About           134
#define MRM_SessionProfile  138
#define MRM_AwayMessage     142
#define MRM_AudioDevices    150
#define MRM_AudioVolume     151

// GUI widgets
#define MRM_CN_SessionContainer 100
#define MRM_CN_BuddyContainer   116
#define MRM_PB_FilterOnline     117
#define MRM_PB_FilterAway       118
#define MRM_PB_FilterOffline    119
#define MRM_ML_IMSender         120

// Dialog Box widgets
#define MRM_LB_SettingsScope      121
#define MRM_EN_ScreenName         122
#define MRM_LB_EventType          123
#define MRM_EN_Password           124
#define MRM_CB_EventPlaySound     125
#define MRM_EN_EventPlaySoundFile 126
#define MRM_CB_EventRunREXX       127
#define MRM_EN_EventRunREXXScript	128
#define MRM_CB_EventRun           129
#define MRM_EN_EventRunCommand    130
#define MRM_PB_UseGlobal          131
#define MRM_ST_SingleEntryLabel   132
#define MRM_EN_SingleEntryField   133
#define MRM_EN_ServerName         135
#define MRM_EN_ServerPort         136
#define MRM_CB_AccountExists      137
#define MRM_CB_EnableTimestamps   139
#define MRM_CB_SessionAutoStart   140
#define MRM_CB_AutoMinimize       141
#define MRM_LB_RecentlyUsedMsgs   143
#define MRM_PB_AddMessage         144
#define MRM_PB_RemoveMessage      145
#define MRM_PB_EditMessage        146
#define MRM_ML_MessageEditor      147
#define MRM_SL_ProgressPercent    148
#define MRM_ST_LoginStep          149
#define MRM_LB_WaveAudioDevice    152
#define MRM_LB_MIDIDevice         153
#define MRM_CS_VolumeKnob         154
#define MRM_CB_TypingNotify       155

HMODULE getModuleHandle( void );

